#!/bin/bash 
compiler="gfortran"
options="-O3"
#options="-fbounds-check -Wno-unused-variable -fimplicit-none -fcheck=all -g -pedantic"
source="ModVec.f90 ModMtrx.f90 Main.f90"
object="ModVec1.o ModMtrx1.o Main1.o -llapack -lblas"
program="Main1.exe"
for file in $source; do
  len=${#file}-4
  $compiler -J./obj -I./obj $options -c $file -o "${file:0:len}1.o"
  if [[ $? != 0 ]]; then
    exit
  fi
done
$compiler -I./obj -o $program $object
./$program
